### ISSUE TITLE
Nav script generation doesn't handle h3

### ISSUE THREAD

**Issue by jordanaubert** [api-platform/website#36]
`index.md`
```markdown
7.  [The Serialization Process](core/serialization.md)
    1.  [Overall Process](core/serialization.md#overall-process)
    2.  [Available Serializers](core/serialization.md#available-serializers)
    3.  [The Serialization Context, Groups and Relations](core/serialization.md#the-serialization-context-groups-and-relations)
        1.  [Configuration](core/serialization.md#configuration)
```
Expected in `nav.yml` : 
```yml
- id: serialization
      title: The Serialization Process
      anchors:
        - id: overall-process
          title: Overall Process
        - id: available-serializers
          title: Available Serializers
        - id: the-serialization-context-groups-and-relations
          title: 'The Serialization Context, Groups and Relations'
          anchors:
            - id: configuration
              title: Configuration
```
